// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: wiKeBsYJZc
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicMicButton2.module.css"; // plasmic-import: wiKeBsYJZc/css

import Mic1SvgIcon from "./icons/PlasmicIcon__Mic1Svg"; // plasmic-import: HqeMbdstf/icon

export type PlasmicMicButton2__VariantMembers = {};

export type PlasmicMicButton2__VariantsArgs = {};
type VariantPropType = keyof PlasmicMicButton2__VariantsArgs;
export const PlasmicMicButton2__VariantProps = new Array<VariantPropType>();

export type PlasmicMicButton2__ArgsType = {};
type ArgPropType = keyof PlasmicMicButton2__ArgsType;
export const PlasmicMicButton2__ArgProps = new Array<ArgPropType>();

export type PlasmicMicButton2__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultMicButton2Props {
  className?: string;
}

function PlasmicMicButton2__RenderFunc(props: {
  variants: PlasmicMicButton2__VariantsArgs;
  args: PlasmicMicButton2__ArgsType;
  overrides: PlasmicMicButton2__OverridesType;
  dataFetches?: PlasmicMicButton2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Mic1SvgIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMicButton2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMicButton2__VariantsArgs;
    args?: PlasmicMicButton2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMicButton2__Fetches;
  } & Omit<PlasmicMicButton2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMicButton2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMicButton2__ArgProps,
      internalVariantPropNames: PlasmicMicButton2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMicButton2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMicButton2";
  } else {
    func.displayName = `PlasmicMicButton2.${nodeName}`;
  }
  return func;
}

export const PlasmicMicButton2 = Object.assign(
  // Top-level PlasmicMicButton2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicMicButton2
    internalVariantProps: PlasmicMicButton2__VariantProps,
    internalArgProps: PlasmicMicButton2__ArgProps
  }
);

export default PlasmicMicButton2;
/* prettier-ignore-end */
