// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: TTI1JEnzco
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicMode.module.css"; // plasmic-import: TTI1JEnzco/css

export type PlasmicMode__VariantMembers = {};

export type PlasmicMode__VariantsArgs = {};
type VariantPropType = keyof PlasmicMode__VariantsArgs;
export const PlasmicMode__VariantProps = new Array<VariantPropType>();

export type PlasmicMode__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicMode__ArgsType;
export const PlasmicMode__ArgProps = new Array<ArgPropType>("children");

export type PlasmicMode__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultModeProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicMode__RenderFunc(props: {
  variants: PlasmicMode__VariantsArgs;
  args: PlasmicMode__ArgsType;
  overrides: PlasmicMode__OverridesType;
  dataFetches?: PlasmicMode__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: "button 1",
        value: args.children,
        className: classNames(sty.slotChildren)
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMode__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMode__VariantsArgs;
    args?: PlasmicMode__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMode__Fetches;
  } & Omit<PlasmicMode__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMode__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMode__ArgProps,
      internalVariantPropNames: PlasmicMode__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMode__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMode";
  } else {
    func.displayName = `PlasmicMode.${nodeName}`;
  }
  return func;
}

export const PlasmicMode = Object.assign(
  // Top-level PlasmicMode renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMode
    internalVariantProps: PlasmicMode__VariantProps,
    internalArgProps: PlasmicMode__ArgProps
  }
);

export default PlasmicMode;
/* prettier-ignore-end */
