// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: adxIUkabTF
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Run from "../../Run"; // plasmic-import: WNRpjvCUBo/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicRunBox.module.css"; // plasmic-import: adxIUkabTF/css

export type PlasmicRunBox__VariantMembers = {};

export type PlasmicRunBox__VariantsArgs = {};
type VariantPropType = keyof PlasmicRunBox__VariantsArgs;
export const PlasmicRunBox__VariantProps = new Array<VariantPropType>();

export type PlasmicRunBox__ArgsType = {};
type ArgPropType = keyof PlasmicRunBox__ArgsType;
export const PlasmicRunBox__ArgProps = new Array<ArgPropType>();

export type PlasmicRunBox__OverridesType = {
  root?: p.Flex<"div">;
  run1?: p.Flex<"div">;
  run2?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultRunBoxProps {
  className?: string;
}

function PlasmicRunBox__RenderFunc(props: {
  variants: PlasmicRunBox__VariantsArgs;
  args: PlasmicRunBox__ArgsType;
  overrides: PlasmicRunBox__OverridesType;
  dataFetches?: PlasmicRunBox__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Run className={classNames("__wab_instance", sty.run__zFjqk)}>
        <div
          data-plasmic-name={"run1"}
          data-plasmic-override={overrides.run1}
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.run1
          )}
        >
          {"run 1"}
        </div>
      </Run>

      <Run className={classNames("__wab_instance", sty.run__bnX2F)}>
        <div
          data-plasmic-name={"run2"}
          data-plasmic-override={overrides.run2}
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.run2
          )}
        >
          {"run 2"}
        </div>
      </Run>

      <Run className={classNames("__wab_instance", sty.run___7Dk5T)}>
        <div
          data-plasmic-name={"box"}
          data-plasmic-override={overrides.box}
          className={classNames(defaultcss.all, defaultcss.__wab_text, sty.box)}
        >
          {"run 3"}
        </div>
      </Run>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "run1", "run2", "box"],
  run1: ["run1"],
  run2: ["run2"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  run1: "div";
  run2: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRunBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRunBox__VariantsArgs;
    args?: PlasmicRunBox__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRunBox__Fetches;
  } & Omit<PlasmicRunBox__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRunBox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRunBox__ArgProps,
      internalVariantPropNames: PlasmicRunBox__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRunBox__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRunBox";
  } else {
    func.displayName = `PlasmicRunBox.${nodeName}`;
  }
  return func;
}

export const PlasmicRunBox = Object.assign(
  // Top-level PlasmicRunBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    run1: makeNodeComponent("run1"),
    run2: makeNodeComponent("run2"),
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicRunBox
    internalVariantProps: PlasmicRunBox__VariantProps,
    internalArgProps: PlasmicRunBox__ArgProps
  }
);

export default PlasmicRunBox;
/* prettier-ignore-end */
