// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: fmg2kCtHOo
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicBadnamebox.module.css"; // plasmic-import: fmg2kCtHOo/css

export type PlasmicBadnamebox__VariantMembers = {};

export type PlasmicBadnamebox__VariantsArgs = {};
type VariantPropType = keyof PlasmicBadnamebox__VariantsArgs;
export const PlasmicBadnamebox__VariantProps = new Array<VariantPropType>();

export type PlasmicBadnamebox__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBadnamebox__ArgsType;
export const PlasmicBadnamebox__ArgProps = new Array<ArgPropType>("children");

export type PlasmicBadnamebox__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBadnameboxProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicBadnamebox__RenderFunc(props: {
  variants: PlasmicBadnamebox__VariantsArgs;
  args: PlasmicBadnamebox__ArgsType;
  overrides: PlasmicBadnamebox__OverridesType;
  dataFetches?: PlasmicBadnamebox__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <input
            className={classNames(defaultcss.input, sty.textbox__rgTi6)}
            placeholder={"name" as const}
            type={"text" as const}
            value={"" as const}
          />
        ),

        value: args.children
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBadnamebox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBadnamebox__VariantsArgs;
    args?: PlasmicBadnamebox__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBadnamebox__Fetches;
  } & Omit<PlasmicBadnamebox__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBadnamebox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBadnamebox__ArgProps,
      internalVariantPropNames: PlasmicBadnamebox__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBadnamebox__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBadnamebox";
  } else {
    func.displayName = `PlasmicBadnamebox.${nodeName}`;
  }
  return func;
}

export const PlasmicBadnamebox = Object.assign(
  // Top-level PlasmicBadnamebox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBadnamebox
    internalVariantProps: PlasmicBadnamebox__VariantProps,
    internalArgProps: PlasmicBadnamebox__ArgProps
  }
);

export default PlasmicBadnamebox;
/* prettier-ignore-end */
