// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: 8CN2TXi9_d
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicCancel.module.css"; // plasmic-import: 8CN2TXi9_d/css

import CancelsvgIcon from "./icons/PlasmicIcon__Cancelsvg"; // plasmic-import: -3S9AjX37/icon

export type PlasmicCancel__VariantMembers = {};

export type PlasmicCancel__VariantsArgs = {};
type VariantPropType = keyof PlasmicCancel__VariantsArgs;
export const PlasmicCancel__VariantProps = new Array<VariantPropType>();

export type PlasmicCancel__ArgsType = {};
type ArgPropType = keyof PlasmicCancel__ArgsType;
export const PlasmicCancel__ArgProps = new Array<ArgPropType>();

export type PlasmicCancel__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultCancelProps {
  className?: string;
}

function PlasmicCancel__RenderFunc(props: {
  variants: PlasmicCancel__VariantsArgs;
  args: PlasmicCancel__ArgsType;
  overrides: PlasmicCancel__OverridesType;
  dataFetches?: PlasmicCancel__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <CancelsvgIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCancel__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCancel__VariantsArgs;
    args?: PlasmicCancel__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCancel__Fetches;
  } & Omit<PlasmicCancel__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCancel__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCancel__ArgProps,
      internalVariantPropNames: PlasmicCancel__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCancel__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCancel";
  } else {
    func.displayName = `PlasmicCancel.${nodeName}`;
  }
  return func;
}

export const PlasmicCancel = Object.assign(
  // Top-level PlasmicCancel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCancel
    internalVariantProps: PlasmicCancel__VariantProps,
    internalArgProps: PlasmicCancel__ArgProps
  }
);

export default PlasmicCancel;
/* prettier-ignore-end */
