// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: uzzvCxxOdE
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicScript.module.css"; // plasmic-import: uzzvCxxOdE/css

export type PlasmicScript__VariantMembers = {};

export type PlasmicScript__VariantsArgs = {};
type VariantPropType = keyof PlasmicScript__VariantsArgs;
export const PlasmicScript__VariantProps = new Array<VariantPropType>();

export type PlasmicScript__ArgsType = {};
type ArgPropType = keyof PlasmicScript__ArgsType;
export const PlasmicScript__ArgProps = new Array<ArgPropType>();

export type PlasmicScript__OverridesType = {
  root?: p.Flex<"textarea">;
};

export interface DefaultScriptProps {
  className?: string;
}

function PlasmicScript__RenderFunc(props: {
  variants: PlasmicScript__VariantsArgs;
  args: PlasmicScript__ArgsType;
  overrides: PlasmicScript__OverridesType;
  dataFetches?: PlasmicScript__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <textarea
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.textarea,
        projectcss.root_reset,
        sty.root
      )}
      placeholder={"your speech here..." as const}
      value={"" as const}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "textarea";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicScript__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicScript__VariantsArgs;
    args?: PlasmicScript__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicScript__Fetches;
  } & Omit<PlasmicScript__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicScript__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicScript__ArgProps,
      internalVariantPropNames: PlasmicScript__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicScript__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicScript";
  } else {
    func.displayName = `PlasmicScript.${nodeName}`;
  }
  return func;
}

export const PlasmicScript = Object.assign(
  // Top-level PlasmicScript renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicScript
    internalVariantProps: PlasmicScript__VariantProps,
    internalArgProps: PlasmicScript__ArgProps
  }
);

export default PlasmicScript;
/* prettier-ignore-end */
