// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: S99cyKldKN
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicFidentiBox.module.css"; // plasmic-import: S99cyKldKN/css

export type PlasmicFidentiBox__VariantMembers = {};

export type PlasmicFidentiBox__VariantsArgs = {};
type VariantPropType = keyof PlasmicFidentiBox__VariantsArgs;
export const PlasmicFidentiBox__VariantProps = new Array<VariantPropType>();

export type PlasmicFidentiBox__ArgsType = {};
type ArgPropType = keyof PlasmicFidentiBox__ArgsType;
export const PlasmicFidentiBox__ArgProps = new Array<ArgPropType>();

export type PlasmicFidentiBox__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultFidentiBoxProps {
  className?: string;
}

function PlasmicFidentiBox__RenderFunc(props: {
  variants: PlasmicFidentiBox__VariantsArgs;
  args: PlasmicFidentiBox__ArgsType;
  overrides: PlasmicFidentiBox__OverridesType;
  dataFetches?: PlasmicFidentiBox__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, defaultcss.__wab_text, sty.box)}
      >
        {"fidenti"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFidentiBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFidentiBox__VariantsArgs;
    args?: PlasmicFidentiBox__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFidentiBox__Fetches;
  } & Omit<PlasmicFidentiBox__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFidentiBox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFidentiBox__ArgProps,
      internalVariantPropNames: PlasmicFidentiBox__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFidentiBox__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFidentiBox";
  } else {
    func.displayName = `PlasmicFidentiBox.${nodeName}`;
  }
  return func;
}

export const PlasmicFidentiBox = Object.assign(
  // Top-level PlasmicFidentiBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicFidentiBox
    internalVariantProps: PlasmicFidentiBox__VariantProps,
    internalArgProps: PlasmicFidentiBox__ArgProps
  }
);

export default PlasmicFidentiBox;
/* prettier-ignore-end */
