// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: fmg2kCtHOo
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicNameBox.module.css"; // plasmic-import: fmg2kCtHOo/css

export type PlasmicNameBox__VariantMembers = {};

export type PlasmicNameBox__VariantsArgs = {};
type VariantPropType = keyof PlasmicNameBox__VariantsArgs;
export const PlasmicNameBox__VariantProps = new Array<VariantPropType>();

export type PlasmicNameBox__ArgsType = {};
type ArgPropType = keyof PlasmicNameBox__ArgsType;
export const PlasmicNameBox__ArgProps = new Array<ArgPropType>();

export type PlasmicNameBox__OverridesType = {
  root?: p.Flex<"div">;
  textbox?: p.Flex<"input">;
};

export interface DefaultNameBoxProps {
  className?: string;
}

function PlasmicNameBox__RenderFunc(props: {
  variants: PlasmicNameBox__VariantsArgs;
  args: PlasmicNameBox__ArgsType;
  overrides: PlasmicNameBox__OverridesType;
  dataFetches?: PlasmicNameBox__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <input
        data-plasmic-name={"textbox"}
        data-plasmic-override={overrides.textbox}
        className={classNames(defaultcss.input, sty.textbox)}
        placeholder={"" as const}
        size={1 as const}
        type={"text" as const}
        value={"name" as const}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "textbox"],
  textbox: ["textbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  textbox: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNameBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNameBox__VariantsArgs;
    args?: PlasmicNameBox__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicNameBox__Fetches;
  } & Omit<PlasmicNameBox__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNameBox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNameBox__ArgProps,
      internalVariantPropNames: PlasmicNameBox__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicNameBox__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNameBox";
  } else {
    func.displayName = `PlasmicNameBox.${nodeName}`;
  }
  return func;
}

export const PlasmicNameBox = Object.assign(
  // Top-level PlasmicNameBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textbox: makeNodeComponent("textbox"),

    // Metadata about props expected for PlasmicNameBox
    internalVariantProps: PlasmicNameBox__VariantProps,
    internalArgProps: PlasmicNameBox__ArgProps
  }
);

export default PlasmicNameBox;
/* prettier-ignore-end */
