// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: k35rev7lCb
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicBack.module.css"; // plasmic-import: k35rev7lCb/css

import BackArrowsvgIcon from "./icons/PlasmicIcon__BackArrowsvg"; // plasmic-import: tCcSNI0-Q/icon

export type PlasmicBack__VariantMembers = {};

export type PlasmicBack__VariantsArgs = {};
type VariantPropType = keyof PlasmicBack__VariantsArgs;
export const PlasmicBack__VariantProps = new Array<VariantPropType>();

export type PlasmicBack__ArgsType = {};
type ArgPropType = keyof PlasmicBack__ArgsType;
export const PlasmicBack__ArgProps = new Array<ArgPropType>();

export type PlasmicBack__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultBackProps {
  className?: string;
}

function PlasmicBack__RenderFunc(props: {
  variants: PlasmicBack__VariantsArgs;
  args: PlasmicBack__ArgsType;
  overrides: PlasmicBack__OverridesType;
  dataFetches?: PlasmicBack__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <BackArrowsvgIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBack__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBack__VariantsArgs;
    args?: PlasmicBack__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBack__Fetches;
  } & Omit<PlasmicBack__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBack__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBack__ArgProps,
      internalVariantPropNames: PlasmicBack__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBack__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBack";
  } else {
    func.displayName = `PlasmicBack.${nodeName}`;
  }
  return func;
}

export const PlasmicBack = Object.assign(
  // Top-level PlasmicBack renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBack
    internalVariantProps: PlasmicBack__VariantProps,
    internalArgProps: PlasmicBack__ArgProps
  }
);

export default PlasmicBack;
/* prettier-ignore-end */
