// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: jFhxioJa-O
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicModeTitle2.module.css"; // plasmic-import: jFhxioJa-O/css

export type PlasmicModeTitle2__VariantMembers = {};

export type PlasmicModeTitle2__VariantsArgs = {};
type VariantPropType = keyof PlasmicModeTitle2__VariantsArgs;
export const PlasmicModeTitle2__VariantProps = new Array<VariantPropType>();

export type PlasmicModeTitle2__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicModeTitle2__ArgsType;
export const PlasmicModeTitle2__ArgProps = new Array<ArgPropType>("children");

export type PlasmicModeTitle2__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultModeTitle2Props {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicModeTitle2__RenderFunc(props: {
  variants: PlasmicModeTitle2__VariantsArgs;
  args: PlasmicModeTitle2__ArgsType;
  overrides: PlasmicModeTitle2__OverridesType;
  dataFetches?: PlasmicModeTitle2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: "classic",
        value: args.children,
        className: classNames(sty.slotChildren)
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicModeTitle2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicModeTitle2__VariantsArgs;
    args?: PlasmicModeTitle2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicModeTitle2__Fetches;
  } & Omit<PlasmicModeTitle2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicModeTitle2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicModeTitle2__ArgProps,
      internalVariantPropNames: PlasmicModeTitle2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicModeTitle2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicModeTitle2";
  } else {
    func.displayName = `PlasmicModeTitle2.${nodeName}`;
  }
  return func;
}

export const PlasmicModeTitle2 = Object.assign(
  // Top-level PlasmicModeTitle2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicModeTitle2
    internalVariantProps: PlasmicModeTitle2__VariantProps,
    internalArgProps: PlasmicModeTitle2__ArgProps
  }
);

export default PlasmicModeTitle2;
/* prettier-ignore-end */
