// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: UZJ7ivhMO2J
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Home from "../../Home"; // plasmic-import: yXGuMQsgCK/component
import Mode from "../../Mode"; // plasmic-import: TTI1JEnzco/component
import ModeTitle2 from "../../ModeTitle2"; // plasmic-import: jFhxioJa-O/component
import NameBox from "../../NameBox"; // plasmic-import: fmg2kCtHOo/component
import MicButton2 from "../../MicButton2"; // plasmic-import: wiKeBsYJZc/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicMode3.module.css"; // plasmic-import: UZJ7ivhMO2J/css

export type PlasmicMode3__VariantMembers = {};

export type PlasmicMode3__VariantsArgs = {};
type VariantPropType = keyof PlasmicMode3__VariantsArgs;
export const PlasmicMode3__VariantProps = new Array<VariantPropType>();

export type PlasmicMode3__ArgsType = {};
type ArgPropType = keyof PlasmicMode3__ArgsType;
export const PlasmicMode3__ArgProps = new Array<ArgPropType>();

export type PlasmicMode3__OverridesType = {
  root?: p.Flex<"div">;
  home?: p.Flex<typeof Home>;
  classic?: p.Flex<typeof Mode>;
  umolympics?: p.Flex<typeof Mode>;
  recitation?: p.Flex<typeof Mode>;
  analysis?: p.Flex<typeof Mode>;
  modeTitle2?: p.Flex<typeof ModeTitle2>;
  nameBox?: p.Flex<typeof NameBox>;
  micButton2?: p.Flex<typeof MicButton2>;
  textbox?: p.Flex<"input">;
};

export interface DefaultMode3Props {
  className?: string;
}

function PlasmicMode3__RenderFunc(props: {
  variants: PlasmicMode3__VariantsArgs;
  args: PlasmicMode3__ArgsType;
  overrides: PlasmicMode3__OverridesType;
  dataFetches?: PlasmicMode3__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.box__hmGWl)}>
            <Home
              data-plasmic-name={"home"}
              data-plasmic-override={overrides.home}
              className={classNames("__wab_instance", sty.home)}
            />

            <div className={classNames(defaultcss.all, sty.box__nLtAv)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__wrsTo)}
              >
                <Mode
                  data-plasmic-name={"classic"}
                  data-plasmic-override={overrides.classic}
                  className={classNames("__wab_instance", sty.classic)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___3Elo
                    )}
                  >
                    {"classic"}
                  </div>
                </Mode>

                <Mode
                  data-plasmic-name={"umolympics"}
                  data-plasmic-override={overrides.umolympics}
                  className={classNames("__wab_instance", sty.umolympics)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___0EZdw
                    )}
                  >
                    {"um olympics"}
                  </div>
                </Mode>

                <Mode
                  data-plasmic-name={"recitation"}
                  data-plasmic-override={overrides.recitation}
                  className={classNames("__wab_instance", sty.recitation)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__xvz9W
                    )}
                  >
                    {"recitation"}
                  </div>
                </Mode>

                <Mode
                  data-plasmic-name={"analysis"}
                  data-plasmic-override={overrides.analysis}
                  className={classNames("__wab_instance", sty.analysis)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__t0Pnf
                    )}
                  >
                    {"analysis"}
                  </div>
                </Mode>
              </p.Stack>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__fttse)}
            >
              <ModeTitle2
                data-plasmic-name={"modeTitle2"}
                data-plasmic-override={overrides.modeTitle2}
                className={classNames("__wab_instance", sty.modeTitle2)}
              />

              <NameBox
                data-plasmic-name={"nameBox"}
                data-plasmic-override={overrides.nameBox}
                className={classNames("__wab_instance", sty.nameBox)}
              />

              <MicButton2
                data-plasmic-name={"micButton2"}
                data-plasmic-override={overrides.micButton2}
                className={classNames("__wab_instance", sty.micButton2)}
              />
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.box__wb6F1)}>
              <input
                data-plasmic-name={"textbox"}
                data-plasmic-override={overrides.textbox}
                className={classNames(defaultcss.input, sty.textbox)}
                placeholder={"" as const}
                size={1 as const}
                type={"text" as const}
                value={"your speech here..." as const}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "home",
    "classic",
    "umolympics",
    "recitation",
    "analysis",
    "modeTitle2",
    "nameBox",
    "micButton2",
    "textbox"
  ],
  home: ["home"],
  classic: ["classic"],
  umolympics: ["umolympics"],
  recitation: ["recitation"],
  analysis: ["analysis"],
  modeTitle2: ["modeTitle2"],
  nameBox: ["nameBox"],
  micButton2: ["micButton2"],
  textbox: ["textbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  home: typeof Home;
  classic: typeof Mode;
  umolympics: typeof Mode;
  recitation: typeof Mode;
  analysis: typeof Mode;
  modeTitle2: typeof ModeTitle2;
  nameBox: typeof NameBox;
  micButton2: typeof MicButton2;
  textbox: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMode3__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMode3__VariantsArgs;
    args?: PlasmicMode3__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMode3__Fetches;
  } & Omit<PlasmicMode3__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMode3__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMode3__ArgProps,
      internalVariantPropNames: PlasmicMode3__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMode3__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMode3";
  } else {
    func.displayName = `PlasmicMode3.${nodeName}`;
  }
  return func;
}

export const PlasmicMode3 = Object.assign(
  // Top-level PlasmicMode3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    home: makeNodeComponent("home"),
    classic: makeNodeComponent("classic"),
    umolympics: makeNodeComponent("umolympics"),
    recitation: makeNodeComponent("recitation"),
    analysis: makeNodeComponent("analysis"),
    modeTitle2: makeNodeComponent("modeTitle2"),
    nameBox: makeNodeComponent("nameBox"),
    micButton2: makeNodeComponent("micButton2"),
    textbox: makeNodeComponent("textbox"),

    // Metadata about props expected for PlasmicMode3
    internalVariantProps: PlasmicMode3__VariantProps,
    internalArgProps: PlasmicMode3__ArgProps
  }
);

export default PlasmicMode3;
/* prettier-ignore-end */
