// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wNxtZcFa8F4mXc5wMcFAw1
// Component: fCWWx9yiYh
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fidenti.module.css"; // plasmic-import: wNxtZcFa8F4mXc5wMcFAw1/projectcss
import * as sty from "./PlasmicBox.module.css"; // plasmic-import: fCWWx9yiYh/css

export type PlasmicBox__VariantMembers = {};

export type PlasmicBox__VariantsArgs = {};
type VariantPropType = keyof PlasmicBox__VariantsArgs;
export const PlasmicBox__VariantProps = new Array<VariantPropType>();

export type PlasmicBox__ArgsType = {};
type ArgPropType = keyof PlasmicBox__ArgsType;
export const PlasmicBox__ArgProps = new Array<ArgPropType>();

export type PlasmicBox__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBoxProps {
  className?: string;
}

function PlasmicBox__RenderFunc(props: {
  variants: PlasmicBox__VariantsArgs;
  args: PlasmicBox__ArgsType;
  overrides: PlasmicBox__OverridesType;
  dataFetches?: PlasmicBox__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__nNwog)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__abhBt
          )}
        >
          {"name"}
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.box__d4SiJ)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__wiqzK
          )}
        >
          {"number"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBox__VariantsArgs;
    args?: PlasmicBox__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBox__Fetches;
  } & Omit<PlasmicBox__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBox__ArgProps,
      internalVariantPropNames: PlasmicBox__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBox__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBox";
  } else {
    func.displayName = `PlasmicBox.${nodeName}`;
  }
  return func;
}

export const PlasmicBox = Object.assign(
  // Top-level PlasmicBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBox
    internalVariantProps: PlasmicBox__VariantProps,
    internalArgProps: PlasmicBox__ArgProps
  }
);

export default PlasmicBox;
/* prettier-ignore-end */
